### ISSUE TITLE
getting this working with github enterprise

### ISSUE THREAD

**Issue by saraf** [Strider-CD/strider-github#50]
I have set up GH Enterprise (trial for 45 days) on a VM.

Am setting the ENV variables and running strider as follows:
```
PLUGIN_GITHUB_API_ENDPOINT="http://192.168.56.105/api/v3" DB_URI="mongodb://strider:devpass@localhost/strider" DEBUG=superagent,strider-github:* node ./bin/strider --no-cluster
```
When trying to add a Github account gets me to an error page
```
2015-08-20T07:25:52.301Z - error: InternalOAuthError: Failed to fetch user profile
    at /noderoot/strider-github/node_modules/passport-github/lib/strategy.js:95:19
    at passBackControl (/noderoot/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:123:9)
    at IncomingMessage.<anonymous> (/noderoot/strider-github/node_modules/passport-github/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:142:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

So, what are the steps needed to get this working with github enterprise?

**Comment by saraf** [comment]
![gh enterprise](https://cloud.githubusercontent.com/assets/117493/9378137/00e12a2a-475a-11e5-97bc-751f9e3cad36.PNG)

**Comment by knownasilya** [comment]
I'm not aware if anyone has ever used Github Enterprise with Strider successfully, if they have, then it looks like a possible API change?

**Comment by saraf** [comment]
I saw a couple of commits - https://github.com/Strider-CD/strider-github/commit/39345dd3c72a73fa150a6d08487619c51cfc3fe2
and 
https://github.com/Strider-CD/strider-github/commit/0abde9aef27a2bcaece596ab681f0b36cb08e56e
(however, parts of those commits are now gone from the code - in https://github.com/Strider-CD/strider-github/commit/d40401074b2bac2b2e94a687ffa559ce0f3c56ef)

Also saw - http://strider.readthedocs.org/en/latest/intro.html#github-github-enterprise-bitbucket
and, a reference in the code - https://github.com/Strider-CD/strider-github/blob/master/lib/api.js#L406-L409
(However, this code is unlikely to work - since we do not get a uri in the  res.request anymore.)

Is it okay to then remove those lines in api.js that are dead - so that someone who will implement github enterprise support will have a clean start?

**Comment by knownasilya** [comment]
Can you add a `// TODO: add enterprise support` line where you remove those lines? Thanks.

**Comment by saraf** [comment]
done!

**Comment by apiv** [comment]
With some local modifications, I've gotten strider-github to connect to our enterprise github server. I'm working on making more appropriate modifications right now, and should have a pull request up in the next few days.

Basically, what needs to be done:

   - [ ] **api.js:423** - here we are assuming that the team id is the /a/b/*this*. All enterprise api urls start with /api/v3, so all we need to do is add a replace('/api/v3/', '') to 421.
   - [ ] **webapp.js** - the appConfig object needs to use the environment variable overrides, if necessary
   - [ ] all situations where github.com is used need to be made dynamic, to either use the environment override or github.com.
   - [ ] Docs need to be updated with steps on setting up the app, etc.

Anyways, I really like the Strider-CD project so far. It's a huge step up from jenkins, and has a UI that I can actually... use.

**Comment by knownasilya** [comment]
Glad to have you onboard @apiv! Looking forward to your PRs.

We already have an issue about using a github API module here: https://github.com/Strider-CD/strider-github/issues/1 but we would still need to keep the `gitane` module around. If you want to tackle this, go for it. I'll try to help as much as possible.

**Comment by apiv** [comment]
Cool, I've made #56 to add enterprise support without the API refactor. I still want to take a shot at refactoring the API to use octonode, I'm just still getting acquainted with passport and the Strider-CD api. I might have some questions along the way, so I'll open a new issue for 'Use octonode' when I get started.

**Comment by apiv** [comment]
#56 merged, this issue should be all set to close.

**Comment by knownasilya** [comment]
I'll close this once I release the GE changes.
