### ISSUE TITLE
Github auth callback url issue

### ISSUE THREAD

**Issue by boo1ean** [Strider-CD/strider-github#55]
Seems like `strider-github` doesn't use `SERVER_NAME` to build github auth callback url.

It always redirects me to localhost.

Bitbucket integration works well though.

**Comment by midgethoen** [comment]
I have this same issue..  i'm trying to figure out how I am supposed to configure this.

**Comment by knownasilya** [comment]
@midgethoen have you updated your github in the Strider "Plugins" page?

**Comment by tomhallam** [comment]
Also having this issue

**Comment by mastertinner** [comment]
+1

**Comment by knownasilya** [comment]
Found a workaround. Use the following ENVs to configure github:

```
PLUGIN_GITHUB_APP_ID
PLUGIN_GITHUB_APP_SECRET
```

Along with `SERVER_NAME`. Looks like there is a check for plugins, which are
found by the `PLUGIN_<pluginname>` env prefix and then Github config is fixed. Will look into this some more later.

**Comment by knownasilya** [comment]
Could someone post how they start strider, with the envs (you can blank them out if they are sensitive)?

**Comment by mastertinner** [comment]
`export SERVER_NAME = "https://strider.scapp.io"`
`export DB_URI = [my_mongo_uri]`
`export SMTP_HOST = "smtp.mailgun.org"`
`export SMTP_USER = [my_mailgun_username]`
`export SMTP_PASS = [my_mailgun_password]`
`NODE_ENV=production npm start`

**Comment by knownasilya** [comment]
^ ok yes you are missing the two ENVs for setting up the github plugin, see https://github.com/Strider-CD/strider-github/issues/55#issuecomment-171649444

**Comment by emcniece** [comment]
Hit this while doing some Nginx proxy shenanigans, and exporting `SERVER_NAME` worked after realizing that it needs to be set to the publicly-facing connection, not the internal one.

I am using [this upstart script](https://fosterelli.co/creating-a-private-ci-with-strider.html#create-the-strider-upstart-job).

- The upstart script was exporting "http://123.456.1.2:4000"
- Github auth endpoint was "http://123.456.1.2/auth/github/callback"
- Nginx conf:

```
server {
    listen 80;
    server_name 123.456.1.2;

    access_log  /var/log/nginx/strider.access.log;
    error_log  /var/log/nginx/strider.error.log;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header HOST $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://123.456.1.2:4000;
        proxy_redirect off;
    }
}
```

... and the problem was that the upstart script should have exported `http://123.456.1.2`, _without_ the port.

On a side note, I'm not able to upgrade the system's `strider-github` package because the strider user doesn't auto-sudo. Weird.

**Comment by knownasilya** [comment]
@alexfernandez could you put a `console.log(rc)` here (after the `if`): https://github.com/Strider-CD/strider/blob/master/lib/libconfig.js#L69 and run the app and post the results (make sure to obscure sensitive info) here.

**Comment by alexfernandez** [comment]
The problem is that Strider is changing the env variable `SERVER_NAME` to `strider_server_name` [here]. I have fixed it with this PR: https://github.com/Strider-CD/strider-github/pull/59.

**Comment by knownasilya** [comment]
That is how `rc` works, so it shouldn't be a problem. Try master with something like `DEBUG=strider:config PLUGIN_GITHUB_TEST=test SERVER_NAME=blah npm start`

**Comment by alexfernandez** [comment]
Actually, that is what I am seeing in my [version 1.7.5](https://github.com/Strider-CD/strider/blob/v1.7.5/lib/libconfig.js#L103), just installed with `npm install strider`.

**Comment by alexfernandez** [comment]
You are right, the change referenced above is unnecessary.

The problem was that, if you use a domain different than `localhost:3000`, you need to add your own developer integration as explained [here](https://github.com/Strider-CD/strider-github#enterprise-setup). Novice error, but it shows as a redirect to `http://localhost:3000` since this is the default declared callback URL for the default client ID. Hope this helps someone else.

**Comment by asayuki** [comment]
This is still an issue. I've tried the solution above and it does not work. Still getting localhost:3000 in my callback URL.

**Comment by knownasilya** [comment]
Did you update to 1.7.6?

**Comment by asayuki** [comment]
Running 1.7.6 yes.

Bitbucket is working fine, but Github not so much.

**Comment by knownasilya** [comment]
So I cannot reproduce this issue. I'll try do a fresh setup this weekend. Any help in narrowing down where the issue is, would be very appreciated.

**Comment by asayuki** [comment]
Sorry, I've got it to work now. Misplaced characters in ENV.

By starting the application by using `SERVER_NAME=http://my.address PLUGIN_GITHUB_APP_ID=<myAppID> PLUGIN_GITHUB_APP_SECRET=<myAppSecret> node bin/strider` I got it to work.

Might be worthwhile to update the README and state that `ID` and `SECRET` must be present for it to work, instead of optional.

**Comment by knownasilya** [comment]
The should be optional as of 1.7.6.. will look into that.

**Comment by midgethoen** [comment]
@knownasilya sry, I missed your question and should have updated my question anyway. Yes, I upgraded the github plugi, which -- I believe -- fixed the issue for me.

**Comment by JKY** [comment]
@asayuki , it works

**Comment by crobinson42** [comment]
FYI - I was running strider 1.7.7 and everything worked fine with the basic env vars (no github_app_id or secret). I ended up reinstalling and got strider v1.8.0 and now it's required that I set `github_app_id` & `github_secret` in order for github plugin to work.
